### ISSUE TITLE
Grade: Exceeds Expectations

### ISSUE THREAD

**Issue by Rodrigap** [NadimRai/CodeAcademy-TeaCozy#3]
Really good job with this project! All of your HTML and CSS is completely functional and beautiful; you used proper HTML tags and CSS selectors, and your code organization is perfect. I generally only give out exceeds expectations grades when people add additional styles/fonts/design elements, but I'm giving it to you because I really couldn't find a single error. Awesome job! For the future, remember that if you want an added challenge you can always add extra style elements that aren't on the spec. Feel free to change up the colors or add CSS animations!

**Comment by NadimRai** [comment]
Thank you for your comment.
